# -*- coding: utf-8 -*-
"""Python_Basics_Gayathri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFNIAdVL0oxRsP8G__irlIeirAkLDhFp

#Create variables to store a person's name (string), age (integer), height in meters (float),
# and whether they are a student (boolean). Print all four values in a single print() statement.'''
"""

name = "Alice"
age = 30
height = 1.65
is_student = True
print(f"Name:{name} , Age:{age} , Height:{height} , Is Student:{is_student}")

"""#Task 2: String Formatting Using the variables from Task 1, print a sentence in the following format:
#  Name: <name> | Age: <age> | Height: <height> | Student: <is_student>
"""

name = "Alice"
age = 30
height = 1.65
is_student = True
print (f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

"""Task 3: Arithmetic Operations Using the age variable, calculate and print:

Age in months
Age in days (assume 365 days/year)
The remainder when age is divided by 7
Age raised to the power of 2 bold text
"""

age = 33
print(f"ActualAge: {age}")
age_in_months = age * 12
print(f"AgeinMonths: {age_in_months}")
age_in_days = age * 365
print(f"AgeinDays: {age_in_days}")
age_remainder = (age// 7)
print(f"AgeRemainder: {age_remainder}")
age_raised_2 = (age ** 2)
print(f"age_raised_2: {age_raised_2}")